=== Pan-Canadian-Genome-Library/data-dictionary/song_schema/json-schema/full/sequenceAlignment.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "properties": {
    "analysisType": {
      "additionalProperties": false,
      "description": "The type of analysis that was performed.",
      "properties": {
        "name": {
          "const": "sequenceAlignment"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    },
    "data_category": {
      "description": "",
      "enum": [
        "Genomics",
        "Transcriptomics",
        "Proteomics",
        "Epigenomics",
        "Imaging",
        "Reference"
      ],
      "type": "string"
    },
    "files": {
      "description": "The list of files associated with the analysis.",
      "items": {
        "additionalProperties": false,
        "description": "Contains information about the files generated from a run of sequencing or data analysis",
        "properties": {
          "dataType": {
            "description": "",
            "enum": [
              "Aligned Reads",
              "Aligned Reads Index"
            ],
            "type": "string"
          },
          "fileAccess": {
            "description": "The permission level of a file for public access.",
            "type": "string"
          },
          "fileMd5sum": {
            "description": "Computed md5sum of the file.",
            "pattern": "^[a-fA-F0-9]{32}$",
            "type": "string"
          },
          "fileName": {
            "description": "Name of the file.",
            "pattern": "^[A-Za-z0-9_\\.\\-\\[\\]\\(\\)]+$.",
            "type": "string"
          },
          "fileSize": {
            "description": "Size of the file, in bytes.",
            "type": "integer"
          },
          "fileType": {
            "description": "Data format of files.",
            "type": "string",
            "enum": [
              "BAM",
              "CRAM",
              "BAI",
              "CRAI"
            ]
          }
        },
        "required": [
          "dataType",
          "fileAccess",
          "fileMd5sum",
          "fileName",
          "fileSize",
          "fileType"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "genome_build": {
      "description": "",
      "enum": [
        "GRCh38",
        "GRCh37"
      ],
      "type": "string"
    },
    "studyId": {
      "description": "Unique identifier of the study.",
      "type": "string"
    },
    "submitter_analysis_id": {
      "description": "Unique identifier of the analysis within the study, assigned by the data provider.",
      "pattern": "^[A-Za-z0-9\\-\\._]{1,64}$",
      "type": "string"
    },
    "submitter_experiment_id": {
      "description": "Unique identifier of the experiment within the study, assigned by the data provider.",
      "pattern": "^[A-Za-z0-9\\-\\._]{1,64}$",
      "type": "string"
    },
    "workflow": {
      "additionalProperties": false,
      "description": "Contains information about the analysis workflow generating the analysis",
      "properties": {
        "submitter_workflow_id": {
          "description": "Indicate the unique identifier of the data processing workflow used in the analysis.",
          "type": "string"
        },
        "workflow_name": {
          "description": "The name of the genomic data processing workflow used for data analysis.",
          "type": "string"
        },
        "workflow_url": {
          "description": "A URL linking to the workflow's repository or documentation. This could be a reference to a GitHub repository, a website where the workflow is described, or documentation on how to run the workflow.",
          "type": [
            "string",
            "null"
          ]
        },
        "workflow_version": {
          "description": "The version of the workflow or pipeline being used. ",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "submitter_workflow_id",
        "workflow_name"
      ],
      "type": "object"
    }
  },
  "required": [
    "submitter_experiment_id",
    "workflow",
    "genome_build",
    "studyId",
    "analysisType",
    "submitter_analysis_id",
    "data_category",
    "files"
  ],
  "type": "object"
}

=== Pan-Canadian-Genome-Library/data-dictionary/test_data/molecular_data_submission/cram/sequenceAlignmentPayload.json
{
  "analysisType": {
    "name": "sequenceAlignment"
  },
  "data_category": "Genomics",
  "files": [
    {
      "dataType": "Aligned Reads",
      "fileAccess": "controlled",
      "fileMd5sum": "0d1776d44d8da87758d6b159aa8e6bc5",
      "fileName": "anon_chr1_completeA.cram",
      "fileSize": 132507,
      "fileType": "CRAM"
    },
    {
      "dataType": "Aligned Reads",
      "fileAccess": "controlled",
      "fileMd5sum": "0a60cf4ee4f7693c3c3fa209246608cb",
      "fileName": "anon_chr1_completeA.cram.crai",
      "fileSize": 67,
      "fileType": "CRAI"
    }
  ],
  "genome_build": "GRCh37",
  "studyId": "test-001",
  "submitter_analysis_id": "analysis_003",
  "submitter_experiment_id": "exp_003",
  "workflow": {
    "submitter_workflow_id": "workflow_001",
    "workflow_name": "DNA Seq Alignment",
    "workflow_url": "https://github.com/icgc-argo-workflows/dna-seq-processing-wfs",
    "workflow_version": "1.9.2"
  }
}
